# -*- coding: utf-8 -*-
"""Product_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZbKrNyH5s7Fev-e-Jsw3lSPLPgcQ5y3g
"""

# Scheduled for incrementally load data daily at 6am IST.
jdbc_url = f"jdbc:sqlserver://{jdbc_hostname}:{jdbc_port};database={jdbc_database};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"

connection_properties = {
    "user": jdbc_username,
    "password": jdbc_password,
    "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}

# Read table from Azure SQL Database = historical_orders
df = spark.read.jdbc(
    url=jdbc_url,
    table="dbo.products_catalog",
    properties=connection_properties
)

# Write table from Azure SQL Database to databricks catalog in delta format = restaurants
df.write \
  .format("delta") \
  .mode("overwrite") \
  .option("overwriteSchema", "true") \
  .saveAsTable("project_catalog.01_bronze.products_catalog")